### ISSUE TITLE
EROOR - Docker

### ISSUE THREAD

**Issue by froeder** [codate/cluster#1]
When I try to run the ```docker-compose pull``` command, the following error is returned:

<pre>
Pulling mongo     ... done
Pulling exam      ... error
Pulling auth      ... done
Pulling file      ... done
Pulling gateway   ... done
Pulling portainer ... done

ERROR: for exam  repository codate/exam not found: does not exist or no pull access
ERROR: repository codate/exam not found: does not exist or no pull access
</pre>

**Comment by charlesviegas** [comment]
There isn't any repository for exam. So I created one. Its working now, can you try again, please?
